FROM base

COPY ci /ci

COPY batch/setup.py /batch/
COPY batch/MANIFEST.in /batch/
COPY batch/batch /batch/batch/
RUN pip3 install --no-cache-dir /batch

COPY requirements.txt .
RUN python3 -m pip install --no-cache-dir -U -r requirements.txt

EXPOSE 5000

CMD ["python3", "-c", "import ci; ci.run()"]
