COPY_TEST_SPECS = [{'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'IsADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/x', '/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/x', '/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'IsADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'IsADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'IsADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'IsADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'IsADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'IsADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/a', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/a', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/a', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'IsADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/a', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/a', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/keep', '/x/a', '/a/subdir/file2', '/a/file3'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/keep', '/x/a', '/a/subdir/file2', '/a/file3'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/keep', '/x/a', '/a/subdir/file2', '/a/file3'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/x', '/keep', '/a/subdir/file2', '/a/file3'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/keep', '/x/a', '/a/subdir/file2', '/a/file3'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/x', '/keep', '/a/subdir/file2', '/a/file3'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'IsADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a', '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a', '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a', '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a', '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/x', '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/x', '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'file',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/subdir/file2', '/keep', '/file1', '/a'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/subdir/file2', '/keep', '/file1', '/a'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'NotADirectoryError'},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/a', '/x/a/file1'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/a', '/x/a/file1'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/a', '/x/a/file1'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/a', '/x/a/file1'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/a', '/x/a/file1'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/file1', '/a', '/x/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/a', '/x/a/file1'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/file1', '/a', '/x/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/a', '/x/a/file1'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/file1', '/a', '/x/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/a', '/x/a/file1'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'files': {'/keep', '/x/file1', '/a', '/x/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/file1',
                       '/keep',
                       '/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/file1',
                       '/keep',
                       '/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file1', '/a/file3', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/a/file1',
                       '/a/a/subdir/file2',
                       '/a/file3',
                       '/a/subdir/file2',
                       '/keep'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/a/file1',
                       '/x/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/a/file1',
                       '/x/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/a/file1',
                       '/x/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/a/file1',
                       '/x/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/a/file1',
                       '/x/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/file1',
                       '/x/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/a/file1',
                       '/x/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/file1',
                       '/x/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/a/file1',
                       '/x/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/file1',
                       '/x/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/a/file1',
                       '/x/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'files': {'/a/file3',
                       '/a/subdir/file2',
                       '/keep',
                       '/x/file1',
                       '/x/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/subdir/file2', '/keep', '/file1'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/subdir/file2', '/keep', '/file1'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a/file1', '/keep', '/a/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a/file1', '/keep', '/a/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a/file1', '/keep', '/a/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a/file1', '/keep', '/a/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a/file1', '/keep', '/a/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a/file1', '/keep', '/a/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a/file1', '/keep', '/a/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/a/a/file1', '/keep', '/a/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/a/file1', '/keep', '/a/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/x/a/file1'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/x/a/file1'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/x/a/file1'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/x/a/file1'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/x/a/file1'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/file1', '/x/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/x/a/file1'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/file1', '/x/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/x/a/file1'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/file1', '/x/subdir/file2'}},
  'src_trailing_slash': True,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/a/subdir/file2', '/x/a/file1'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'files': {'/keep', '/x/file1', '/x/subdir/file2'}},
  'src_trailing_slash': False,
  'src_type': 'dir',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'file',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'dir',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': None,
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'a',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_dir'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'target_file'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': True,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': True,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'},
 {'dest_basename': 'x',
  'dest_trailing_slash': False,
  'dest_type': 'noexist',
  'result': {'exception': 'FileNotFoundError'},
  'src_trailing_slash': False,
  'src_type': 'noexist',
  'treat_dest_as': 'infer_target'}]
