DROP TABLE IF EXISTS `jobs`;
DROP TABLE IF EXISTS `batch-attributes`;
DROP TABLE IF EXISTS `jobs-parents`;
DROP TABLE IF EXISTS `batch`;
DROP TABLE IF EXISTS `pods`;
DROP TABLE IF EXISTS `instances`;
