FROM {{ base_image.image }}

COPY hail/python/setup-hailtop.py /hailtop/setup.py
COPY hail/python/hailtop /hailtop/hailtop/
RUN python3 -m pip install --no-cache-dir /hailtop \
  && rm -rf /hailtop

COPY batch2/test/ /test/
RUN python3 -m pip install --no-cache-dir \
  pytest-instafail==0.4.1 \
  pytest-asyncio==0.10.0

CMD ["python3", "-m", "pytest", "--log-cli-level=INFO", "-s", "-vv", "--instafail", "-k", "not test_scale", "/test/"]
