version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/docker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "pip"
    directory: "/hail/python"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "pip"
    directory: "/hail/python/dev"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "gradle"
    directory: "/hail"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
