#!/bin/sh
# POSIX non-interactive shells do not guarantee any file to be loaded so there
# is no profile or rc file that we can reliably put this line into

try_source() {
    [ -e "$1" ] && . "$1"
}

if ! conda activate 2>/dev/null
then
    try_source /opt/conda/etc/profile.d/conda.sh || \
        try_source "${HOME}/anaconda2/etc/profile.d/conda.sh" || \
        try_source "${HOME}/miniconda/etc/profile.d/conda.sh" || \
        (if which conda >/dev/null 2>/dev/null
         then
             conda_dir=$(dirname $(dirname $(which conda)))
             try_source "$conda_dir/etc/profile.d/conda.sh"
         else
             exit 1
         fi)
fi
