#!/bin/sh
# until-with-fuel N COMMAND ARGS ...
#
# Executes `COMMAND ARGS ...`, at most N times, until it returns a non-zero exit
# code. If `COMMAND ARGS ...` is executed N times and never returns a non-zero
# exit code, until-with-fuel will exit with the last code returned by the
# command
#
# Set DELAY to control how long until-with-fuel waits between calls to
# `COMMAND ARGS ...`.
#
# This script is intended to be POSIX compliant.

set -e

DELAY=${DELAY:-1}
MAX_TRIES=${MAX_TRIES:-$1}

shift

: $((tries = 0))
until "$@" >/dev/null 2>&1
do
    : $((tries = tries + 1)) && [ $tries -lt ${MAX_TRIES} ]
    sleep ${DELAY}
done
