apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-fetcher
  labels:
    app: image-fetcher
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: image-fetcher
  template:
    metadata:
      labels:
        app: image-fetcher
        hail.is/sha: "{{ code.sha }}"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      containers:
      - name: image-fetcher
        image: "{{ image_fetcher_image.image }}"
        resources:
          requests:
            cpu: 1m
            memory: 100Mi
        volumeMounts:
         - name: deploy-config
           mountPath: /deploy-config
         - name: docksock
           mountPath: /var/run/docker.sock
         - name: gcr-pull-key
           mountPath: /secrets
         - name: ssl-config-image-fetcher
           mountPath: /ssl-config
           readOnly: true
      volumes:
       - name: deploy-config
         secret:
           secretName: deploy-config
       - name: docksock
         hostPath:
           path: /var/run/docker.sock
       - name: gcr-pull-key
         secret:
           optional: False
           secretName: gcr-pull-key
       - name: ssl-config-image-fetcher
         secret:
           optional: false
           secretName: ssl-config-image-fetcher
