FROM spark-base

COPY environment.yml /
RUN conda env create -f /environment.yml && \
    rm -f /environment.yml

COPY build/hail /hail
RUN cp /hail/jars/hail-all-spark.jar $SPARK_HOME/jars/hail-all-spark.jar

ENV HAIL_HOME /hail
ENV PYTHONPATH "$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.4-src.zip:$HAIL_HOME/python"
ENV PYSPARK_SUBMIT_ARGS "--conf spark.kryo.registrator=is.hail.kryo.HailKryoRegistrator pyspark-shell"
