FROM hail-base

COPY apiserver /apiserver
COPY hailjwt /hailjwt
RUN (cd /hailjwt && python3 setup.py .)

ENV HAIL_SPARK_PROPERTIES "spark.driver.host=apiserver,spark.driver.bindAddress=0.0.0.0,spark.driver.port=9001,spark.blockManager.port=9002"

CMD ["/bin/bash", "-c", "python3 /apiserver/apiserver.py"]
