FROM {{ hail_run_image.image }}

COPY hail.zip .
RUN unzip -q hail.zip && \
  mv hail inner && \
  mkdir -p /hail/python && \
  mv inner /hail/python/hail

COPY hail-all-spark.jar /hail/jars/hail-all-spark.jar
RUN cp /hail/jars/hail-all-spark.jar $SPARK_HOME/jars/hail-all-spark.jar

ENV HAIL_HOME /hail
ENV PYTHONPATH "${PYTHONPATH:+${PYTHONPATH}:}$HAIL_HOME/python"
ENV PYSPARK_SUBMIT_ARGS "--conf spark.kryo.registrator=is.hail.kryo.HailKryoRegistrator pyspark-shell"
