FROM base

COPY requirements.txt .
RUN python3 -m pip install --no-cache-dir -U -r requirements.txt

COPY build/hail /hail
RUN cp /hail/jars/hail-all-spark.jar $SPARK_HOME/jars/hail-all-spark.jar

ENV HAIL_HOME /hail
ENV PYTHONPATH "$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.7-src.zip:$HAIL_HOME/python"
ENV PYSPARK_SUBMIT_ARGS "--conf spark.kryo.registrator=is.hail.kryo.HailKryoRegistrator pyspark-shell"
