FROM alpine:3.8

RUN apk add --no-cache \
  g++ \
  gcc \
  libc-dev \
  make \
  py3-cffi \
  py3-cryptography \
  python3 \
  python3-dev \
  && true

COPY setup.py /batch/
COPY batch /batch/batch/
RUN pip3 install --no-cache-dir /batch
COPY test /test

CMD ["python3", "-m", "unittest", "-v", "/test/test_batch.py"]
