apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-gateway-envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 8080
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: AUTO
              stat_prefix: ingress_http
              upgrade_configs:
                - upgrade_type: websocket
              use_remote_address: true
              skip_xff_append: false
              access_log:
                name: json_error_access_log
                filter:
                  status_code_filter:
                    comparison:
                      op: GE  # >=
                      value:
                        runtime_key: "500"
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                  log_format:
                    json_format:
                      message: "%LOCAL_REPLY_BODY%"
                      status: "%RESPONSE_CODE%"
                      duration: "%DURATION%"
                      remote_address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                      x_real_ip: "%REQ(X-Real-IP)%"
                      request_start_time: "%START_TIME%"
                      bytes_sent: "%BYTES_SENT%"
                      http_referer: "%REQ(Referer)%"
                      http_user_agent: "%REQ(User-Agent)%"
              rds:
                route_config_name: https_routes
                config_source:
                  resource_api_version: V3
                  path_config_source:
                    path: /config_map/xds/rds.yaml
                    watched_directory:
                      path: /config_map/xds
              http_filters:
                - name: envoy.filters.http.local_ratelimit
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
                    stat_prefix: http_local_rate_limiter
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8001
    layered_runtime:
      layers:
      - name: static_layer_0
        static_layer:
          envoy:
            resource_limits:
              listener:
                example_listener_name:
                  connection_limit: 10000
    dynamic_resources:
      cds_config:
        resource_api_version: V3
        path_config_source:
          path: /config_map/xds/cds.yaml
          watched_directory:
            path: /config_map/xds
