FROM {{ base_image.image }}

COPY hailjwt/setup.py /hailjwt/
COPY hailjwt/hailjwt /hailjwt/hailjwt/
RUN pip3 install --no-cache-dir /hailjwt && \
  rm -rf /hailjwt

COPY batch_client/setup.py /batch_client/
COPY batch_client/batch_client /batch_client/batch_client
RUN pip3 install --no-cache-dir /batch_client && \
  rm -rf /batch_client

COPY pipeline/setup.py /pipeline/
COPY pipeline/pipeline /pipeline/pipeline/
RUN pip3 install --no-cache-dir /pipeline && \
  rm -rf /pipeline

COPY pipeline/test /test/

CMD ["python3", "-m", "pytest", "-v", "-s", "/test/"]
