CREATE TABLE ci_events (
  id BIGINT NOT NULL AUTO_INCREMENT,
  time TIMESTAMP(3) NOT NULL DEFAULT (UTC_TIMESTAMP(3)),
  event ENUM(
    'merge_requested',
    'merge_pending',
    'merge_succeeded',
    'merge_failed',
    'merge_expired',
    'merge_cleared',
    'merge_restored',
    'build_requested',
    'build_started',
    'build_start_failed',
    'build_cancelled',
    'retry_requested',
    'sha_authorized',
    'frozen',
    'unfrozen',
    'dev_deploy_requested',
    'update_triggered',
    'target_moved',
    'deploy_started',
    'deploy_start_failed',
    'deploy_finished',
    'deploy_failure_alerted',
    'deploy_status_failed',
    'reviewer_assigned',
    'reviewer_assign_failed',
    'status_post_failed',
    'ci_started',
    'update_failed',
    'namespace_created',
    'namespace_deleted',
    'service_added',
    'service_edited',
    'service_deleted',
    'namespace_expired_cleanup'
  ) NOT NULL,
  target_branch VARCHAR(255),
  pr_number INT,
  username VARCHAR(255),
  batch_id BIGINT,
  source_sha VARCHAR(40),
  target_sha VARCHAR(40),
  previous_sha VARCHAR(40),
  namespace VARCHAR(255),
  service VARCHAR(255),
  merge_uuid VARCHAR(64),
  message TEXT,
  PRIMARY KEY (id),
  INDEX ci_events_branch (target_branch, id),
  INDEX ci_events_branch_pr (target_branch, pr_number, id),
  INDEX ci_events_event (event, id),
  INDEX ci_events_time (time)
) ENGINE = InnoDB;
