CREATE INDEX aggregated_billing_project_user_resources_v3_token ON `aggregated_billing_project_user_resources_v3` (`token`);
CREATE INDEX aggregated_billing_project_user_resources_by_date_v3_token ON `aggregated_billing_project_user_resources_by_date_v3` (`token`);
