DROP TRIGGER IF EXISTS aggregated_bp_user_resources_v2_before_insert;
DROP TRIGGER IF EXISTS aggregated_bp_user_resources_by_date_v2_before_insert;
DROP TRIGGER IF EXISTS aggregated_job_group_resources_v2_before_insert;
DROP TRIGGER IF EXISTS aggregated_job_resources_v2_before_insert;

DROP TRIGGER IF EXISTS aggregated_bp_user_resources_v2_after_update;
DROP TRIGGER IF EXISTS aggregated_bp_user_resources_by_date_v2_after_update;
DROP TRIGGER IF EXISTS aggregated_job_group_resources_v2_after_update;
DROP TRIGGER IF EXISTS aggregated_job_resources_v2_after_update;

DROP TABLE IF EXISTS aggregated_billing_project_user_resources_v2;
DROP TABLE IF EXISTS aggregated_billing_project_user_resources_by_date_v2;
DROP TABLE IF EXISTS aggregated_job_group_resources_v2;
DROP TABLE IF EXISTS aggregated_job_resources_v2;
