{
 "title": "Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kubernetes apiserver requests/s",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count[5m]))"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_duration_microseconds{quantile=\"0.99\"})",
     "legendFormat": "mean"
    },
    {
     "expr": "max(http_request_duration_microseconds{quantile=\"0.99\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "available"
    },
    { "expr": "sum(node_load1)", "legendFormat": "1m load average" },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Pods (Stacked)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(kube_node_info)" }
   ]
  },
  {
   "title": "PV Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_persistentvolume_capacity_bytes)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Persistent Volumes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_persistentvolume_labels)",
     "legendFormat": "Persistent Volumes"
    },
    {
     "expr": "count(kube_persistentvolumeclaim_labels)",
     "legendFormat": "Persistent Volume Claims"
    }
   ]
  },
  {
   "title": "Batch Request latency by endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(batch_request_latency_seconds_sum[10m])) by (endpoint) / sum(rate(batch_request_latency_seconds_count[10m])) by (endpoint)"
    }
   ]
  },
  {
   "title": "Batch Request Count by Endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(batch_request_latency_seconds_count[10m])) by (endpoint)"
    }
   ]
  }
 ]
}