name: Bug Report
description: Report a bug
labels: needs-triage
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also, what did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Hail are you using?
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. If too large, please put in https://gist.github.com and provide the link.
      render: shell
