apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-pod
  template:
    metadata:
      labels:
        app: admin-pod
    spec:
      nodeSelector:
        preemptible: "true"
      tolerations:
       - key: preemptible
         value: "true"
       - key: "kubernetes.azure.com/scalesetpriority"
         value: "spot"
      containers:
       - name: admin-pod
         command:
          - bash
          - -c
          - "while true; do sleep 1000; done"
         image: {{ admin_pod_image.image }}
         resources:
           requests:
             cpu: "1m"
             memory: "2M"
           limits:
             cpu: "1"
             memory: "1G"
         volumeMounts:
          - name: deploy-config
            mountPath: /deploy-config
            readOnly: true
          - name: sql-config
            mountPath: /sql-config
            readOnly: true
          - name: ssl-config-curlrc
            mountPath: /root/.curlrc
            subPath: .curlrc
            readOnly: true
          - name: mysql-cnf
            mountPath: /root/.my.cnf
            subPath: .my.cnf
            readOnly: true
      volumes:
       - name: deploy-config
         secret:
           secretName: deploy-config
       - name: sql-config
         secret:
           secretName: database-server-config
       - name: mysql-cnf
         secret:
           secretName: database-server-config
           items:
             - key: sql-config.cnf
               path: .my.cnf
       - name: ssl-config-curlrc
         secret:
           optional: false
           secretName: ssl-config-admin-pod
           items:
             - key: ssl-config.curlrc
               path: .curlrc
