FROM {{ hail_ubuntu_image.image }}

RUN hail-apt-get-install \
    git \
    htop \
    unzip bzip2 zip tar \
    rsync \
    emacs-nox \
    xsltproc pandoc \
    openjdk-8-jdk-headless \
    liblapack3 \
    liblz4-dev \
    g++-10 \
    gcc-10 \
    cmake \
    && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
