FROM {{ base_image.image }}

COPY hail/python/setup-hailtop.py /hailtop/setup.py
COPY hail/python/hailtop /hailtop/hailtop/
RUN python3 -m pip install --no-deps --no-cache-dir /hailtop \
  && rm -rf /hailtop

COPY gear/setup.py /gear/setup.py
COPY gear/gear /gear/gear/
RUN python3 -m pip install --no-deps --no-cache-dir /gear \
  && rm -rf /gear
