ARG BASE_IMAGE={{ hail_ubuntu_image.image }}
FROM $BASE_IMAGE

RUN hail-apt-get-install \
    git \
    htop \
    unzip bzip2 zip tar \
    xsltproc pandoc \
    openjdk-21-jdk-headless \
    liblapack3 \
    liblz4-dev \
    make

RUN hail-pip-install build
