apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuffler
  labels:
    app: shuffler
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: shuffler
  replicas: 1
  template:
    metadata:
      labels:
        app: shuffler
        hail.is/sha: "{{ code.sha }}"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      containers:
        - name: shuffler
          image: "{{ shuffler_image.image }}"
          command:
{% if not deploy %}
            - /controller.sh
{% endif %}
            - java
            - -cp
            - /usr/local/lib/python3.7/dist-packages/pyspark/jars/*:/hail.jar
            - is.hail.services.shuffler.server.ShuffleServer
          env:
           - name: HAIL_DOMAIN
             value: "{{ global.domain }}"
           - name: HAIL_DEPLOY_CONFIG_FILE
             value: /deploy-config/deploy-config.json
           - name: HAIL_SHA
             value: "{{ code.sha }}"
          ports:
           - containerPort: 443
          volumeMounts:
           - name: deploy-config
             mountPath: /deploy-config
             readOnly: true
           - name: ssl-config
             mountPath: /ssl-config
             readOnly: true
          resources:
            requests:
              cpu: "600m"
              memory: "2G"
            limits:
              cpu: "1"
              memory: "2.5G"
      volumes:
       - name: deploy-config
         secret:
           secretName: deploy-config
       - name: ssl-config
         secret:
           optional: false
           secretName: ssl-config-shuffler
---
apiVersion: v1
kind: Service
metadata:
  name: shuffler
  labels:
    app: shuffler
spec:
  ports:
  - name: shuffler
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: shuffler
