FROM {{ base_image.image }}

RUN apt-get update && \
  apt-get -y install \
    liblz4-dev \
    maven

COPY pom.xml test-jar-with-dependencies.xml
RUN mvn dependency:resolve && \
  rm pom.xml test-jar-with-dependencies.xml
