FROM {{ hail_ubuntu_image.image }}

ENV LANG C.UTF-8

RUN hail-apt-get-install openjdk-8-jdk-headless

COPY hail/python/requirements.txt requirements.txt
COPY hail/python/dev-requirements.txt dev-requirements.txt
RUN hail-pip-install -r requirements.txt -r dev-requirements.txt

COPY wheel-container.tar wheel-container.tar
RUN tar -xf wheel-container.tar && \
    hail-pip-install hail-*-py3-none-any.whl

COPY pylintrc setup.cfg /
