FROM {{ hail_ubuntu_image.image }}

RUN apt-get update && \
  apt-get -y install \
    openjdk-8-jdk-headless \
    python3.6 python3-pip \
  && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 \
  && rm -rf /var/lib/apt/lists/*

COPY hail/python/requirements.txt requirements.txt
COPY hail/python/dev-requirements.txt dev-requirements.txt
RUN hail-pip-install -r requirements.txt -r dev-requirements.txt

COPY wheel-container.tar wheel-container.tar
RUN tar -xf wheel-container.tar && \
    hail-pip-install hail-*-py3-none-any.whl

COPY pylintrc setup.cfg /
