FROM {{ base_image.image }}

RUN hail-apt-get-install liblz4-dev maven

RUN hail-pip-install pyspark==3.2.1
ENV SPARK_HOME /usr/local/lib/python3.7/dist-packages/pyspark
ENV PATH "$PATH:$SPARK_HOME/sbin:$SPARK_HOME/bin"
ENV PYSPARK_PYTHON python3

COPY docker/core-site.xml ${SPARK_HOME}/conf/core-site.xml
