FROM {{ base_image.image }}
ENV PYTHONPATH ""
RUN hail-apt-get-install liblz4-dev
COPY wheel-container.tar ./
RUN tar -xf wheel-container.tar && \
    pip3 install -U hail-*-py3-none-any.whl && \
    rm -rf hail-*-py3-none-any.whl
