FROM bitnami/minideb:buster

ENV LANG C.UTF-8

RUN echo 'deb http://ftp.us.debian.org/debian stretch main' >> /etc/apt/sources.list && \
  install_packages \
    openjdk-8-jdk-headless \
    python3.6 python3-pip \
  && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1

COPY hail/python/requirements.txt requirements.txt
COPY hail/python/dev-requirements.txt dev-requirements.txt
RUN python3 -m pip install -U setuptools -r requirements.txt -r dev-requirements.txt

COPY wheel-container.tar wheel-container.tar
RUN tar -xf wheel-container.tar && \
    python3 -m pip install hail-*-py3-none-any.whl

COPY pylintrc setup.cfg /
