FROM {{ hail_ubuntu_image.image }}

ENV LANG C.UTF-8
RUN hail-apt-get-install \
    openjdk-8-jdk-headless \
    python3.8 python3-pip \
  && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1

COPY hail/python/dev/pinned-requirements.txt dev-requirements.txt
RUN hail-pip-install -r dev-requirements.txt

RUN --mount=src=wheel-container.tar,target=/wheel-container.tar \
    tar -xf wheel-container.tar && \
    hail-pip-install hail-*-py3-none-any.whl

COPY pylintrc setup.cfg /
