FROM ubuntu:18.04

ENV LANG C.UTF-8

RUN echo "APT::Acquire::Retries \"3\";" > /etc/apt/apt.conf.d/80-retries && \
  apt-get update && \
  apt-get -y install \
    openjdk-8-jdk-headless \
    python3.6 python3-pip \
  && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 \
  && rm -rf /var/lib/apt/lists/*

COPY hail/python/requirements.txt requirements.txt
COPY hail/python/dev-requirements.txt dev-requirements.txt
RUN python3 -m pip install -U -r requirements.txt -r dev-requirements.txt

COPY wheel-container.tar wheel-container.tar
RUN tar -xf wheel-container.tar && \
    python3 -m pip install hail-*-py3-none-any.whl

COPY pylintrc setup.cfg /
