FROM {{ service_base_image.image }}

ENV PYTHONPATH ""
RUN hail-apt-get-install liblz4-dev

COPY python/pinned-requirements.txt requirements.txt
COPY python/dev/pinned-requirements.txt dev-requirements.txt
RUN file=$(mktemp) && \
    cat requirements.txt dev-requirements.txt > $file && \
    hail-pip-install -r $file

RUN --mount=src=hail.whl,target=/hail.whl \
    hail-pip-install --no-deps hail.whl
