FROM {{ hail_ubuntu_image.image }}

ENV LANG C.UTF-8

RUN hail-apt-get-install openjdk-8-jdk-headless

COPY hail/python/pinned-requirements.txt requirements.txt
COPY hail/python/dev/pinned-requirements.txt dev-requirements.txt
RUN file=$(mktemp) && \
    cat requirements.txt dev-requirements.txt > $file && \
    hail-pip-install -r $file

RUN --mount=src=hail.whl,target=/hail.whl \
    hail-pip-install --no-deps hail.whl

COPY pylintrc setup.cfg /
