apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-agent
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: ci-agent-token
  annotations:
    kubernetes.io/service-account.name: ci-agent
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-agent
rules:
- apiGroups: [""]
  resources: ["services", "pods", "pods/log", "secrets", "configmaps"]
  verbs: ["*"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ci-agent
subjects:
- kind: ServiceAccount
  name: ci-agent
roleRef:
  kind: Role
  name: ci-agent
  apiGroup: ""
