GITHUB_API_URL = 'https://api.github.com/'
GITHUB_CLONE_URL = 'https://github.com/'
VERSION = '0-1'
CONTEXT = 'hail-ci-0-1'
BUILD_JOB_PREFIX = 'hail-ci-0-2-1'
BUILD_JOB_TYPE = BUILD_JOB_PREFIX + '-build'
DEPLOY_JOB_TYPE = BUILD_JOB_PREFIX + '-deploy'
GCP_PROJECT = 'broad-ctsa'
GCS_BUCKET = 'hail-ci-' + VERSION
SHA_LENGTH = 12
