FROM {{ service_base_image.image }}

RUN apt-get update && \
  apt-get -y install docker.io && \
  rm -rf /var/lib/apt/lists/*

RUN hail-pip-install twine

COPY jinja2_render.py .
COPY wait-for.py .
COPY create_database.py .
