#!/bin/bash
set -ex

git clone $SOURCE_REPO_URL \
    --branch $SOURCE_BRANCH \
    repo
cd repo
git remote add target $TARGET_REPO_URL
git fetch target $TARGET_BRANCH
echo $(git rev-parse target/$TARGET_BRANCH)
echo $(git rev-parse $SOURCE_BRANCH)
[[ $( git rev-parse $SOURCE_BRANCH ) == $SOURCE_SHA ]]
[[ $( git rev-parse target/$TARGET_BRANCH ) == $TARGET_SHA ]]
git config user.email hail-ci-pr-builder@hail.is
git config user.name "Hail CI PR Builder"
git checkout target/$TARGET_BRANCH && git merge $SOURCE_BRANCH
chmod 755 ./hail-ci-build.sh

set +e
./hail-ci-build.sh
BUILD_EXIT=$?
set -e

if [[ -e artifacts ]]; then
    DEST=gs://hail-ci-0-1/ci/$SOURCE_SHA/$TARGET_SHA
    gcloud auth activate-service-account \
           hail-ci-0-1@broad-ctsa.iam.gserviceaccount.com \
           --key-file=/secrets/hail-ci-0-1.key
    gsutil -m \
           -q \
           -h "Cache-Control:private, max-age=0, no-transform" \
           cp -r \
           artifacts/ \
           $DEST/
    gsutil -m acl ch -r -u AllUsers:R $DEST/
    for f in $(find artifacts/ -name '*.log' -print); do
        gsutil setmeta -h "Content-Type: text/plain" $DEST/$f
    done
fi

exit $BUILD_EXIT
