apiVersion: v1
kind: Pod
metadata:
  name: letsencrypt
  labels:
    app: letsencrypt
spec:
  serviceAccountName: letsencrypt
  tolerations:
   - key: preemptible
     value: "false"
  containers:
  - name: letsencrypt
    image: {{ letsencrypt_image.image }}
    command:
      - "/bin/sh"
      - "/revoke-certs.sh"
    env:
      - name: "CERT_IDS_TO_REVOKE"
        value: {{ cert_ids_to_revoke }}
    ports:
    - containerPort: 80
  restartPolicy: Never
