name: Build pip package
on:
  # Building on pull-requests and pushes to main, but restricting publishing 
  # to push events with `if: github.event_name == 'push'` for specific steps
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@main

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Hail builds only on java=8
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      # Building the wheel.
      # Note that because PyPI doesn't have channels like conda, we have to prefix 
      # the package name with "cpg-*" to avoid clashing with the official package.
      - name: Build wheel
        run: |
          sed -i 's/name="hail",/name="cpg-hail",/' hail/python/setup.py
          make -C hail python-version-info wheel

      - name: Install
        run: |
          version=$(cat hail/python/hail/hail_pip_version)
          pip install hail/build/deploy/dist/cpg_hail-$version-py3-none-any.whl

      - name: Test hailctl
        run: hailctl version

      - name: Test hailtop import
        run: python -c "import hailtop.batch"

      - name: Test version
        run: test "$(hailctl version)" = "$(cat hail/python/hail/hail_version)"
  
      - name: Publish the wheel to PyPI
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: hail/build/deploy/dist/
          skip_existing: true

      - name: Redeploy the analysis-server
        if: github.event_name == 'push'
        run: |
          echo "version=$(cat hail/python/hail/hail_pip_version)" >> $GITHUB_ENV
          curl --fail --silent --show-error -X POST \
            -H "Authorization: token ${{ secrets.ANALYSIS_SERVER_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/populationgenomics/analysis-runner/actions/workflows/6364059/dispatches \
            -d '{"ref": "main", "inputs": {"hail_version": "${{ env.version }}"}}'
