name: Trigger AppSec Review Check

on:
  pull_request_review:
    types: [submitted, edited, dismissed]

# Minimal permissions needed, no permission to create a status check
permissions:
  pull-requests: write

jobs:
  add-trigger-label:
    name: Add Trigger Label
    runs-on: ubuntu-latest
    # Prevent running on forks since they won't have access to secrets
    if: github.repository == 'hail-is/hail'
    
    steps:
      - name: Add trigger label
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Check if the label already exists on the PR
          if ! gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json labels --jq '.labels[] | select(.name == "needs-appsec-review-checker")' | grep -q "needs-appsec-review-checker"; then
            echo "Adding needs-appsec-review-checker label to trigger review check..."
            gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --add-label "needs-appsec-review-checker"
          else
            echo "Label already exists on PR"
          fi 
